# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 341a32da8903a7597678507a6cb01f61ca383f1862d99b4ef4b22390b86a2b995619803a57b2a7abae977e78adf39015fb4c1ce74a376d3d1ac5e1df9468f0b6

test:
  secret_key_base: 31fb46a986cb54cf90858c38f9d0286d3276940de66d394deb835da61bd13cda213111e0455ba1506472c4dd95a4ae0ceeabd6c5bab8f962f52da01557289094

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
